name: 'CI'

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: private ë ˆí¬ì§€í† ë¦¬ ê°€ì ¸ì˜¤ê¸°
        uses: actions/checkout@v3

      - name: JDK 11ì„ ì„¤ì¹˜
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle ëª…ë ¹ ì‹¤í–‰ì„ ìœ„í•œ ê¶Œí•œì„ ë¶€ì—¬
        run: chmod +x gradlew

      - name: Gradle build ìˆ˜í–‰
        run: ./gradlew build

      - name: í…ŒìŠ¤íŠ¸ ê²°ê³¼
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: JaCoCo Coverage ê²°ê³¼
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: ğŸ“ í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ ë¦¬í¬íŠ¸ì…ë‹ˆë‹¤
          paths: ${{ github.workspace }}/build/jacoco/index.xml
          min-coverage-overall: 80
          min-coverage-changed-files: 70